### ISSUE TITLE
implement cancelAndHoldAtTime

### ISSUE THREAD

**Issue by mmckegg** [mohayonao/pseudo-audio-param#5]
This has recently been added to the spec: https://developer.mozilla.org/en-US/docs/Web/API/AudioParam/cancelAndHoldAtTime

I will try and look into how this could be implemented when I have some time available. 

But @mohayonao if you can see a simple and easy solution, please go ahead, or give me some pointers 😄

**Comment by mohayonao** [comment]
ok, I've implemented cancelAndHoldAtTime. Maybe, this works fine. maybe..

**Comment by mmckegg** [comment]
awesome! Will give it a try this week and let you know 🎉 😀
